### ISSUE TITLE
Not working on ESP32-S3 (N16R8)!!!

### ISSUE THREAD

**Issue by MDRafi08642** [FLOCK4H/AtomDucky#1]
Model: ESP32-S3 N16R8

I have installed CircuitPython 9.0.5.
Copied and pasted all files to the CircuitPython drive.
Plugged and unplugged, but nothing happened.
No access point was created or something.

Here is the content of the boot_out.txt file:
```
Adafruit CircuitPython 9.0.5 on 2024-05-22; VCC-GND YD-ESP32-S3 (N16R8) with ESP32S3
Board ID:yd_esp32_s3_n16r8
UID:085699FD1688
[2K[0Gboot.py output:

```

![Screenshot 2024-08-23 120323](https://github.com/user-attachments/assets/de3305be-8480-4384-810f-e385472207ad)

**Comment by FLOCK4H** [comment]
I'm unable to help you at this point, please have in mind that creating an issue titled "Not working!!!" is very unprofessional, and does imply on others that this project is not up to date.

There are few issues:

1. You didn't share any output, connect to a serial monitor and then restart the board to see what it outputs.

2. Your board may not be compatible, I only found this entry "VCC-GND YD-ESP32-S3 (N16R8)", if that's your board and it's not working, well, revert to point 1.

PS: The output of boot.py is irrelevant, look for output of code.py

Good luck 🍀

**Comment by MDRafi08642** [comment]
@FLOCK4H  Yeah that's the Same model.

And here's the serial output: (uart port COM5)
![Screenshot 2024-08-23 200753](https://github.com/user-attachments/assets/ecaf0f3e-65be-4e3b-b326-12ad7929d30f)

**Comment by MDRafi08642** [comment]
@FLOCK4H  & here's the output using Putty: (usb port COM7)

![Screenshot 2024-08-24 122043](https://github.com/user-attachments/assets/4fbed0f2-5648-4517-bbe4-78946e3ffc71)

I have pressed "any" key, Then ctrl+D.

**Comment by FLOCK4H** [comment]
Great! You have successfully debugged your issue.

Your ESP does not have a button named BTN, so you must modify source code of AtomDucky to reassign the button. 

1. Enter REPL
2. Execute line by line:

```
import board
dir(board)
```

3. Change all BTN pins to another pin name, specific for your board. In my case, the BTN was the main button of AtomS3U. God knows what this button is doing, it's been a while since I used any Ducky.

Happy to see your progress, keep it up.

**Comment by MDRafi08642** [comment]
@FLOCK4H  This is my board: (There are 2 buttons, boot & RST )
![Sa78efe227357474797d6611105da5ecf4 jpg_720x720q80](https://github.com/user-attachments/assets/f129b2fb-8848-4b4b-b790-307136486914)

Here's the output using putty:
![Screenshot 2024-08-24 182230](https://github.com/user-attachments/assets/3e511126-894f-4dd2-b7f8-87f37c3b5afd)

I have replaced "BTN" in with "GPIO12" buttons.py. (Now, working)
But it's a pin, not a button.

**Comment by FLOCK4H** [comment]
It's okay, the button should not be necessary to run AtomDucky, so you're fine with the current setup. 

Can I help you with anything else?
Please close this issue if otherwise.

**Comment by MDRafi08642** [comment]
@FLOCK4H How to stop "BLE" attack On my board?
& how to exit from "Rubber" mode On my board?

**Comment by FLOCK4H** [comment]
> @FLOCK4H How to stop "BLE" attack On my board? & how to exit from "Rubber" mode On my board?

1. By pressing the button. Try to assign BOOT button in place of GPIO12, it may not work, as BOOT may be reserved by CircuitPy to do other stuff.

2. Read **Usage** section of README.md file please.

**Comment by FLOCK4H** [comment]
The initial issue was resolved, I'm closing this. Contact me privately for any further assistance.

**Comment by MDRafi08642** [comment]
@FLOCK4H  I will try.
But you can check issues on RPI pico W board.
Thanks.
