### ISSUE TITLE
 ValueError: Only IPv4 addresses supported (Raspberry Pi Pico W)

### ISSUE THREAD

**Issue by MDRafi08642** [FLOCK4H/AtomDucky#2]
Model: Original Raspberry Pi Pico W.

Note: Due to space issues, I have deleted [logo.svg](https://github.com/FLOCK4H/AtomDucky/blob/main/AtomDucky/static/logo.svg), [favicon.ico](https://github.com/FLOCK4H/AtomDucky/blob/main/AtomDucky/static/favicon.ico), [ducky.svg](https://github.com/FLOCK4H/AtomDucky/blob/main/AtomDucky/atoms/website_atoms/ducky.svg).

I have also modified "buttons.py":
```
import digitalio, board
from neopixel import NeoPixel

pixel = NeoPixel(board.GP13, 1, brightness=0.2)
button = digitalio.DigitalInOut(board.GP12)
```

Everything should work fine, but there was an error: `ValueError: Only IPv4 addresses supported`.

Serial monitor via Putty:
![Screenshot 2024-08-24 213934](https://github.com/user-attachments/assets/1230c596-b6d5-456f-97f9-a3c0e7891c02)

**Comment by FLOCK4H** [comment]
This error pops up when there is non-IPv4 address passed, you need to check _config file, make sure the address is in a correct IPv4 format, add a print statement to the code and print the address that is being passed, to make sure that the one from _config file is readable.

**Comment by tzeit** [comment]
> Model: Original Raspberry Pi Pico W.
> 
> Note: Due to space issues, I have deleted [logo.svg](https://github.com/FLOCK4H/AtomDucky/blob/main/AtomDucky/static/logo.svg), [favicon.ico](https://github.com/FLOCK4H/AtomDucky/blob/main/AtomDucky/static/favicon.ico), [ducky.svg](https://github.com/FLOCK4H/AtomDucky/blob/main/AtomDucky/atoms/website_atoms/ducky.svg).
> 
> I have also modified "buttons.py":
> 
> ```
> import digitalio, board
> from neopixel import NeoPixel
> 
> pixel = NeoPixel(board.GP13, 1, brightness=0.2)
> button = digitalio.DigitalInOut(board.GP12)
> ```
> 
> Everything should work fine, but there was an error: `ValueError: Only IPv4 addresses supported`.
> 
> Serial monitor via Putty: ![Screenshot 2024-08-24 213934](https://github.com/user-attachments/assets/1230c596-b6d5-456f-97f9-a3c0e7891c02)

Did you found a solution, got the same issue here
