### ISSUE TITLE
Pico w platformdetect latest package not support your board 

### ISSUE THREAD

**Issue by Shivam00817** [FLOCK4H/AtomDucky#4]
Whenever I try to install atom ducky on my pico w with following every single step and after few when I run the code.py in thonny it shows latest version of platformdetect not support by your board I am stuck at this step please kindly solve my issue as soon as possible so I can use and install your project atom ducky in my pico w 
@FLOCK4H  please solve my issue

**Comment by FLOCK4H** [comment]
Reinstall CircuitPython.

Then enter REPL and:
import board 
print(board)

**Comment by Shivam00817** [comment]
Will you please elaborate I am new at this kind of stuff so please sir ! I understand i have to reinstall circuit python latest version and then where will I enter REPL and :
Import board
Print (board) 
Where will I write above code in python ide ? Please explain sir i appreciate your time @FLOCK4H

**Comment by FLOCK4H** [comment]
Thonny IDE,

For the reference we are in 2024, and I'm not an AI model.

https://chatgpt.com

**Comment by Shivam00817** [comment]
Thanks for your time sir my error is solved now the problem is i didn't switched to cod mode in thonny ide I was running code in regular thonny ide which was default so it was showing the error now when I switched to circuit micro python mode which the at the lower right side of the thonny ide interface and then I run code.py again and now it completely fine and working now my problem is solved I can use atom ducky smoothly now thanks for your time and support

**Comment by FLOCK4H** [comment]
Sure buddy, keep working up ✌️⭐️
