### ISSUE TITLE
Pico w showing as removable drive 

### ISSUE THREAD

**Issue by Shivam00817** [FLOCK4H/AtomDucky#6]
Hello sir @FLOCK4H  sorry for distributing you guys I am almost done and using atom ducky smoothly but there is a problem that whenever I plug my pico w it is showing as removable drive and usb device it's not hiding or we can say it's not acting as hid device because computer is detecting it as a removable drive CIRCUITPY (H;) but everything else like payloads ,live keyboard and all functions are working fine the problem is only that it's not acting as hid computer is detecting it as CIRCUITPY(H:) removable drive please kindly grant me a solution for this issue I used thonny intrepeter and selected micropython raspberry pi pico but still the issue persist one more thing when I connect my pico w with thonny in boot mode I can install micropython for pico w which when installed through thonny ide makes my pico w hid but then I can't code anything else in my pico w it's plain I hope you understand my issue basically my pico w is not acting as hid computer is detecting is everytime

**Comment by FLOCK4H** [comment]
~There's literally a stealthy operation mode mentioned in the readme file.~

~**Solution: README.md**~

Investigating...

**Comment by FLOCK4H** [comment]
Thank you for bringing this up, all this time I was sure that I've added a line to uncomment in `boot.py` that disables usb storage, turns out it was in NeoDucky and not in AtomDucky.

For future reference, this is how it can be done on any MCU:

**In boot.py:**
```
import storage

storage.disable_usb_drive()
```

I will update the AtomDucky soon!
